/**
 * Shared blur-placeholder for `next/image` when we do not have a
 * cached dominant color for the photo.
 *
 * Generated by encoding an 8x5 SVG rectangle of paper-cream
 * (#ECE5D5, the same hex as --app-paper-2) as a data URL. The shape
 * is small enough that the encoded string adds ~140 bytes per
 * `<Image>` and gives the user a calm warm-cream haze before the
 * real photo lands. Better than a white flash, much better than a
 * blank frame.
 *
 * For surfaces that DO have a cached dominant color (SeasonalPhoto
 * uses the manifest's blur hex), prefer that. This is the fallback
 * for Google Place photos and other dynamic URLs where the dominant
 * color is unknown at build time.
 */
export const PAPER_CREAM_BLUR =
  "data:image/svg+xml;base64," +
  Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" width="8" height="5"><rect width="8" height="5" fill="#ECE5D5"/></svg>',
  ).toString("base64");
