import { PLACES, type Place } from "@/data/places";
import { CATEGORY_BY_SLUG } from "@/data/categories";
import { MUNICIPALITY_BY_SLUG } from "@/data/municipalities";
import { eventsAtVenue, type Event } from "@/data/events";
import { haversineMeters, isValidCoord, type LngLat } from "@/lib/geo";
import { categoryFromPrimaryType } from "@/lib/categoryFromGoogle";
import { isNonDiscoverable } from "@/lib/relevance";
import { getOpenStatus, type OpenStatus } from "@/lib/hours";
import { parseGoogleWeekdayHours } from "@/lib/hours-parse";
import { isKnownClosed } from "@/lib/integrations/closures";
import ENRICHMENT_RAW from "@/data/places-enrichment.json" with { type: "json" };
import DEDUP_RAW from "@/data/places-dedup.json" with { type: "json" };
import OVERRIDES_RAW from "@/data/places-overrides.json" with { type: "json" };
import KNOWN_FOR_RAW from "@/data/known-for.json" with { type: "json" };
import { RELIABLE_OPEN_WINDOWS, isLikelyOpenNow } from "@/data/reliable-open-windows";
import { getLandmarkPhoto } from "@/lib/integrations/wikimedia";
import { autoFold } from "@/lib/dedupe";
import { makeResolver, patchRecord, type Overrides } from "@/lib/overrides";

type DedupEntry = { canonical: string; merged?: { website?: string; phone?: string } };
const DEDUP = DEDUP_RAW as Record<string, DedupEntry>;
// Default ON by owner directive (2026-05-16: "ship everything"). The
// dedupe is verified and all named venues fold. Set RADIUS_DEDUPE=0 to
// disable without a code change (instant rollback).
const DEDUPE_ON = process.env.RADIUS_DEDUPE !== "0";

/**
 * Collapse fuzzy duplicates to one canonical record (curated wins) and
 * overlay unique website/phone the canonical was missing. Pure, so it
 * is unit tested. Identity when there is no dedup entry for a slug.
 */
export function applyDedup(list: Place[]): Place[] {
  return list
    .filter((p) => {
      const e = DEDUP[p.slug];
      return !e || e.canonical === p.slug; // drop folded duplicates
    })
    .map((p) => {
      const e = DEDUP[p.slug];
      if (!e?.merged) return p;
      return {
        ...p,
        website: p.website ?? e.merged.website,
        phone: p.phone ?? e.merged.phone,
      };
    });
}

// Urbana was added as a community AFTER the place data was scraped, so
// places physically inside its bounds were tagged to a neighbor and
// /m/urbana, the by-town view, and Radius would be empty for it. Claim
// them by geography so Urbana gets "all the things the other towns
// have". Scoped to Urbana ONLY — deterministic, zero effect on any
// other municipality's set. Composed onto the END of the dedupe +
// overrides pipeline below, so it survives folds/patches.
const URBANA_BBOX = MUNICIPALITY_BY_SLUG["urbana"]?.bbox;
function claimUrbana(p: Place): Place {
  if (!URBANA_BBOX || p.municipality === "urbana") return p;
  const [minLng, minLat, maxLng, maxLat] = URBANA_BBOX;
  const { lng, lat } = p.geom;
  return lng >= minLng && lng <= maxLng && lat >= minLat && lat <= maxLat
    ? { ...p, municipality: "urbana" }
    : p;
}

type Enrichment = {
  business_status?: "OPERATIONAL" | "CLOSED_TEMPORARILY" | "CLOSED_PERMANENTLY" | "UNKNOWN";
  weekday_hours?: string[];
  has_hours?: boolean;
  rating?: number;
  user_rating_count?: number;
  photo_names?: string[];
  phone?: string;
  website?: string;
  lat?: number;
  lng?: number;
  primary_type?: string;
  editorial_summary?: string;
  review_snippet?: string;
  review_author?: string;
  enriched_at?: string;
};
const ENRICHMENT = ENRICHMENT_RAW as Record<string, Enrichment>;

/**
 * AI-extracted "known for" + "customers loved" tags keyed by slug.
 * Generated by scripts/extract-known-for.mjs (gpt-4o-mini via the
 * Vercel AI Gateway). The script is idempotent — re-running only
 * processes slugs not already in the file. Entries with no signal
 * worth surfacing are simply absent.
 */
type KnownFor = {
  known_for?: string[];
  customers_loved?: string[];
  source?: string;
  extracted_at?: string;
};
const KNOWN_FOR = KNOWN_FOR_RAW as Record<string, KnownFor>;

/**
 * The HUMAN data-cleaning layer (places-overrides.json, written by
 * `npm run data:review`). This is how the irreducible judgement tail
 * the safe engine cannot touch — typo dupes ("Summitra" vs "Sumittra
 * Thai Cuisine"), junk records, wrong categories — gets fixed in one
 * place and lands on every surface. Applied HERE so it can never be
 * forgotten by a caller.
 */
const OVERRIDES = OVERRIDES_RAW as Overrides;
const OV_FOLD: Record<string, string> = OVERRIDES.fold ?? {};
const OV_REMOVE: ReadonlySet<string> = new Set(OVERRIDES.remove ?? []);
const OV_KEEP: ReadonlySet<string> = new Set(OVERRIDES.keepApart ?? []);
const OV_PATCH = OVERRIDES.patch;

/**
 * Slugs the automatic engine must never fold away: the curator's
 * `canonical === self` markers in places-dedup.json PLUS every
 * `keepApart` slug in the overrides file. The one-line manual veto.
 */
const PINNED: ReadonlySet<string> = new Set([
  ...Object.entries(DEDUP)
    .filter(([slug, e]) => e.canonical === slug)
    .map(([slug]) => slug),
  ...OV_KEEP,
]);

/**
 * Three-stage cleaning applied HERE, at the one canonical source, so
 * every non-admin surface (Radius/home, Map, Search, Municipality,
 * Saved, Sitemap, Plan) inherits a single reality and the "I keep
 * seeing the same thing twice" problem cannot regress:
 *   1. places-dedup.json — curated legacy human folds.
 *   2. autoFold — the deterministic same-place rule (src/lib/dedupe.ts)
 *      over the survivors, so a NEW exact/variant dupe is collapsed
 *      the moment it enters the data, zero upkeep, safelist-guarded.
 *   3. places-overrides.json — the human judgement tail the safe rule
 *      cannot touch: typo folds, junk removals, field patches. Written
 *      by `npm run data:review`; applied last so a human always wins.
 * Gated by RADIUS_DEDUPE for instant rollback (overrides remove/patch
 * are data corrections and stay honored even then).
 */
const STATIC_DEDUPED: Place[] = DEDUPE_ON ? applyDedup(PLACES) : PLACES;

const AUTO_FOLD: Map<string, string> = DEDUPE_ON
  ? autoFold(
      STATIC_DEDUPED.map((p) => ({
        slug: p.slug,
        name: p.name,
        geom: p.geom,
        source: p.source,
        municipality: p.municipality,
        google_place_id: p.google_place_id,
        feature_score: p.feature_score,
        hasEnrichment: Boolean(ENRICHMENT[p.slug]),
      })),
      PINNED,
    )
  : new Map<string, string>();

// Every slug → its final surviving canonical, chasing human folds
// first, then auto folds, then legacy folds (chain- and cycle-safe).
const DEDUP_AS_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(DEDUP).map(([s, e]) => [s, e.canonical]),
);
const resolveCanonicalSlug = makeResolver([OV_FOLD, AUTO_FOLD, DEDUP_AS_MAP]);

const BASE_PLACES: Place[] = (DEDUPE_ON ? STATIC_DEDUPED : PLACES)
  // Drop anything folded away (auto OR human typo fold) and any
  // human-removed junk; then apply human field patches. remove/patch
  // are data corrections so they apply even with dedupe disabled.
  .filter(
    (p) =>
      !OV_REMOVE.has(p.slug) &&
      (!DEDUPE_ON || (!AUTO_FOLD.has(p.slug) && !OV_FOLD[p.slug])),
  )
  .map((p) => patchRecord(p, OV_PATCH))
  // Urbana geo-claim runs LAST so it composes with dedupe + overrides.
  .map(claimUrbana);

// Build-time visibility into off-bbox places. Server-only so it
// doesn't run in the browser. Same shape as the events placement
// warning so build logs read consistently.
if (typeof window === "undefined") {
  const offBbox = BASE_PLACES.filter((p) => !isValidCoord(p.geom));
  if (offBbox.length > 0) {
    const sample = offBbox.slice(0, 5).map((p) => p.slug).join(", ");
     
    console.warn(
      `[placement] places: ${offBbox.length} row(s) flagged needs_review (off-bbox or missing coord). Examples: ${sample}`,
    );
  }
}

const BASE_BY_SLUG: Record<string, Place> = (() => {
  const byCanon: Record<string, Place> = {};
  for (const p of BASE_PLACES) byCanon[p.slug] = p;
  const idx: Record<string, Place> = { ...byCanon };
  // Every original slug (folded, legacy, typo, old link) resolves to
  // its surviving canonical record. Removed slugs deliberately do not
  // resolve, so getPlaceBySlug returns null and they vanish entirely.
  for (const p of PLACES) {
    if (OV_REMOVE.has(p.slug) || idx[p.slug]) continue;
    const canon = byCanon[resolveCanonicalSlug(p.slug)];
    if (canon) idx[p.slug] = canon;
  }
  return idx;
})();

/** Google-verified data merged onto a place, when available. */
export type PlaceEnriched = {
  /** Proxied photo URL (server route, key-safe) — first photo, for heroes */
  google_photo_url?: string;
  /** All proxied photo URLs (key-safe), for galleries */
  google_photos?: string[];
  google_rating?: number;
  google_rating_count?: number;
  /** Human-readable weekly hours from Google */
  google_hours?: string[];
  /** True once Google has verified this place */
  google_verified?: boolean;
  /** One attributed Google review snippet — "what people say". Shown
   *  as labelled UGC, never as our own description/SEO copy. */
  review_snippet?: string;
  review_author?: string;
  /** Structured signal extracted (by AI) from editorial_summary +
   *  review_snippet — see scripts/extract-known-for.mjs. Surfaced as
   *  a chip strip on /places/[slug] so visitors get the WHAT (food,
   *  experience) without reading a paragraph. Either array may be
   *  empty when the source text was too generic to extract from. */
  known_for?: string[];
  customers_loved?: string[];
  /**
   * ISO date marking when this row was last verified against an
   * authoritative source. Enriched rows: the date of the Google sync
   * batch (constant below, bumped per enrichment run). Curated-only
   * rows: the editor's date. Used by the FreshnessChip on detail.
   */
  last_verified_at?: string;
};

/**
 * Date of the most recent Google enrichment sync. Bump this constant
 * (or wire it to the build pipeline) every time `places-enrichment.json`
 * is regenerated so the UI's freshness chip reflects reality. Curated-
 * only places without enrichment fall back to SEED_VERIFIED_AT below.
 */
const ENRICHMENT_VERIFIED_AT = "2026-05-14T00:00:00Z";
const SEED_PLACE_VERIFIED_AT = "2026-05-14T00:00:00Z";

// Slug is optional but recommended: when included, the photo route uses
// it to render a richer fallback placeholder (place initials + category
// color) on the days Google rotates the underlying photo reference and
// the upstream fetch fails. Without the slug, the placeholder degrades
// to a generic gradient.
const photoProxy = (name: string, w = 800, slug?: string) =>
  `/api/place-photo?name=${encodeURIComponent(name)}&w=${w}${slug ? `&slug=${encodeURIComponent(slug)}` : ""}`;

// Blob-backed photos win over the rotating Google proxy. The download
// script (npm run download:photos) writes src/data/places-photos.json
// mapping slug → public Blob URL. Imported here so the loader resolves
// the right source ONCE per place at build time. Slugs not in the map
// fall through to the proxy.
import { placePhotoBlob } from "@/lib/places-photos";

export type PlaceCardData = Place & PlaceEnriched & {
  open_status: OpenStatus;
  distance_m?: number;
  /** "verified" = Google hours confirm open. "likely" = curated window. */
  open_confidence?: "verified" | "likely";
};

function applyEnrichment(p: Place): Place & PlaceEnriched {
  const e = ENRICHMENT[p.slug];
  if (!e) return { ...p, last_verified_at: SEED_PLACE_VERIFIED_AT };
  // Google business_status overrides our seed guess — it's authoritative.
  const is_operational =
    e.business_status === "CLOSED_PERMANENTLY" ? "closed_permanently" :
    e.business_status === "CLOSED_TEMPORARILY" ? "closed_temporarily" :
    e.business_status === "OPERATIONAL" ? "operational" :
    p.is_operational;
  const photos = (e.photo_names ?? []).slice(0, 8);
  // Pin accuracy: the DFP scrape geocoded ~157 places to the wrong
  // spot (owner verified several on the ground). Google's coordinate
  // for a matched place is authoritative, so snap to it — but ONLY
  // when it is a sane correction (≤2 km from the scrape). ~106
  // enrichments are bad Text-Search matches that resolved a same-name
  // business 3–50 km away; using those would teleport pins across the
  // county. Beyond 2 km we keep the scrape and treat the match as
  // suspect. Every surface (map, radius distance, nearby) inherits
  // this via the one canonical loader.
  const geom =
    typeof e.lat === "number" &&
    typeof e.lng === "number" &&
    haversineMeters(p.geom, { lng: e.lng, lat: e.lat }) <= 2000
      ? { lng: e.lng, lat: e.lat }
      : p.geom;
  // Category correction: Google's primaryType is authoritative — it
  // fixes the DFP miscategorization that no name heuristic can (a
  // coffee shop with no "coffee" in its name, a hotel filed under
  // shopping, etc.). Conservative: only confident Google types map;
  // a vague type returns null and the existing category is kept.
  const category = categoryFromPrimaryType(e.primary_type) ?? p.category;
  // Curated editorial voice (seed/manual) is kept; for DFP + Google-
  // discovered, Google's real one-line description replaces the
  // scraped/placeholder blurb ("Coffee in Thurmont"). Never blank,
  // never fabricated — only a real Google summary wins.
  const short_blurb =
    p.source !== "seed" && p.source !== "manual" && e.editorial_summary?.trim()
      ? e.editorial_summary.trim()
      : p.short_blurb;
  // Hours: curated wins; otherwise parse Google's weekday_hours into
  // structured Hours so the OpenClosedDot at the top of the page
  // matches the table below it. Previously the structured field stayed
  // undefined when only Google data existed, so the page showed
  // "Hours not posted" right above a fully-populated Google hours
  // table — a visible contradiction.
  const hours = p.hours ?? parseGoogleWeekdayHours(e.weekday_hours);
  return {
    ...p,
    geom,
    category,
    short_blurb,
    is_operational,
    // Curated data wins; Google fills the gaps. This is why ~96% of places
    // (DFP scrapes with no phone/site) stay blank until enriched.
    phone: p.phone ?? e.phone,
    website: p.website ?? e.website,
    hours,
    // If Google gave us hours, we consider hours verified.
    hours_verified: e.has_hours ? true : p.hours_verified,
    is_verified: e.business_status === "OPERATIONAL" ? true : p.is_verified,
    // Photo source resolution:
    //   1. Blob URL from the downloader (permanent, never rotates)
    //   2. Live proxy through the API key (rotates every few weeks)
    //   3. undefined (component falls back to category placeholder)
    // The Blob URL is the long-term answer; the proxy is the bridge
    // until the downloader has been run for that slug.
    google_photo_url:
      placePhotoBlob(p.slug) ??
      (photos[0] ? photoProxy(photos[0], 800, p.slug) : undefined),
    // The detail page's photo gallery still uses the proxy for the
    // 2nd-8th photos — the downloader only stores the hero for now.
    // A future pass can extend it to the whole array.
    google_photos: photos.map((n) => photoProxy(n, 800, p.slug)),
    google_rating: e.rating,
    google_rating_count: e.user_rating_count,
    google_hours: e.weekday_hours,
    google_verified: Boolean(e.business_status && e.business_status !== "UNKNOWN"),
    review_snippet: e.review_snippet?.trim() || undefined,
    review_author: e.review_author?.trim() || undefined,
    known_for: KNOWN_FOR[p.slug]?.known_for?.length
      ? KNOWN_FOR[p.slug]?.known_for
      : undefined,
    customers_loved: KNOWN_FOR[p.slug]?.customers_loved?.length
      ? KNOWN_FOR[p.slug]?.customers_loved
      : undefined,
    last_verified_at: ENRICHMENT_VERIFIED_AT,
  };
}

export type PlaceDetail = PlaceCardData & {
  category_name: string;
  municipality_name: string;
  nearby_places: PlaceCardData[];
  upcoming_events: Event[];
};

export function decoratePlace(p: Place, origin?: LngLat, now: Date = new Date()): PlaceCardData {
  const enriched = applyEnrichment(p);
  // Hours provenance, Phase 1 precedence: Google enrichment, then a
  // curated manual schedule. OSM hours apply to the map's OSM layer,
  // not the static place records, so they are not stamped here.
  const e = ENRICHMENT[p.slug];
  const hours_source: Place["hours_source"] = e?.has_hours
    ? "google_places"
    : enriched.hours && enriched.hours_verified
      ? "manual_override"
      : undefined;
  const hours_updated_at =
    hours_source === "google_places"
      ? e?.enriched_at
      : hours_source === "manual_override"
        ? p.updated_at
        : undefined;
  return {
    ...enriched,
    hours_source,
    hours_updated_at,
    open_status: getOpenStatus(enriched.hours, { verified: enriched.hours_verified ?? false }, now),
    distance_m: origin ? haversineMeters(origin, enriched.geom) : undefined,
  };
}

/** Share of places that carry verified hours, for the Open-now gate. */
export function hoursCoverage(places: PlaceCardData[]): number {
  if (!places.length) return 0;
  return places.filter((p) => p.hours_source).length / places.length;
}

// Default ON by owner directive (2026-05-16: "ship everything"). At
// today's ~3.6% verified-hours coverage this hides the Open-now
// affordance widely in favor of an honest message, which is the
// trustworthy behavior the data-layer brief asked for. Set
// HOURS_GATE=0 to restore the always-show behavior (instant rollback).
const HOURS_GATE = process.env.HOURS_GATE !== "0";

/**
 * True when the Open-now affordance should hide because verified-hours
 * coverage for the visible set is under 60 percent. Callers render the
 * STYLE.md message in place of the affordance.
 */
export function shouldHideOpenNow(places: PlaceCardData[]): boolean {
  return HOURS_GATE && hoursCoverage(places) < 0.6;
}

export function getPlaceBySlug(slug: string, origin?: LngLat, now: Date = new Date()): PlaceDetail | null {
  const p = BASE_BY_SLUG[slug];
  if (!p) return null;
  const decorated = decoratePlace(p, origin, now);

  const nearby_places = BASE_PLACES
    .filter((x) => x.slug !== p.slug)
    .filter(isOperational)
    .filter(isDiscoverable)
    .filter(isSubstantive)
    .map((x) => decoratePlace(x, p.geom, now))
    .sort((a, b) => (a.distance_m ?? Infinity) - (b.distance_m ?? Infinity))
    .slice(0, 6);

  return {
    ...decorated,
    category_name: CATEGORY_BY_SLUG[p.category]?.name ?? p.category,
    municipality_name: MUNICIPALITY_BY_SLUG[p.municipality]?.name ?? p.municipality,
    nearby_places,
    upcoming_events: eventsAtVenue(p.slug),
  };
}

export type RankingContext = {
  origin?: LngLat;
  now?: Date;
  preferOpen?: boolean;
  category?: string;
  municipality?: string;
  tags?: string[];
  limit?: number;
};

function proximityScore(distance_m: number | undefined): number {
  if (distance_m === undefined) return 0.5;
  if (distance_m < 500) return 1;
  if (distance_m < 1500) return 0.8;
  if (distance_m < 3000) return 0.6;
  if (distance_m < 8000) return 0.4;
  return 0.2;
}

function openScore(status: OpenStatus): number {
  if (status.state === "open") return 1;
  if (status.state === "closing-soon") return 0.6;
  if (status.state === "unknown") return 0.5;
  return 0;
}

/**
 * The single closed-place predicate. Any surface that renders places
 * must filter through this so closed businesses never display. The
 * Radius page regressed by consuming the raw PLACES array directly.
 */
export function isOperational(p: Place): boolean {
  if (isKnownClosed(p.name)) return false; // manual override of last resort
  // Google enrichment is the SOURCE OF TRUTH for closure. DFP-scraped
  // records hardcode is_operational: "operational" at load time so the
  // raw Place field can lie (Serendipity Market, Brass Copper Shop,
  // …). Read the live enrichment business_status first; only fall
  // back to the Place field when there is no enrichment.
  const e = ENRICHMENT[p.slug];
  if (e?.business_status === "CLOSED_PERMANENTLY") return false;
  if (e?.business_status === "CLOSED_TEMPORARILY") return false;
  return p.is_operational !== "closed_permanently" && p.is_operational !== "closed_temporarily";
}

// Default ON by owner directive (2026-05-17: "hide the businesses most
// people wouldn't look for"). At today's enrichment this quiets ~304
// DFP-scraped B2B/trade/professional/residential records that made the
// product feel like a phone book. Set RADIUS_RELEVANCE=0 to show
// everything again without a code change (instant rollback).
const RELEVANCE_ON = process.env.RADIUS_RELEVANCE !== "0";

/**
 * Discovery-relevance predicate. False ONLY when both guards agree:
 * the record is DFP-scraped (curated seed/manual/GIS is always kept,
 * so a bad Google text-match can't erase it) AND Google's primaryType
 * is an explicit non-discoverable type (B2B / trade / professional-
 * services / residential — see relevance.ts). A vague or missing type
 * is always kept. Used by the list/map/Radius generators below; single-
 * slug retrieval deliberately does NOT use it, so a saved or linked
 * record still resolves — we hide from discovery, never destroy.
 */
export function isDiscoverable(p: Place): boolean {
  if (!RELEVANCE_ON) return true;
  if (p.source !== "dfp") return true; // never hide curated content
  return !isNonDiscoverable(ENRICHMENT[p.slug]?.primary_type);
}

// Default ON (owner: "prune the bare entries", 2026-05-18). Hides the
// ~2% bare-bones discovered tail. Set RADIUS_PRUNE_THIN=0 to disable
// without a code change (instant rollback).
const PRUNE_THIN_ON = process.env.RADIUS_PRUNE_THIN !== "0";

/**
 * Substance predicate. False ONLY for the bare-bones discovered tail:
 * a bulk-scraped/discovered record (dfp|google) with NO Google rating,
 * NO photo, and NO editorial summary — nothing but a name, category
 * and a point. Curated seed/manual is ALWAYS substantive (never hidden
 * by this). Like isDiscoverable: the discovery generators below use
 * it; single-slug retrieval deliberately does NOT, so a saved or
 * linked record still resolves — we hide from discovery, never
 * destroy. Cheap: reads the enrichment map, never decorates.
 */
export function isSubstantive(p: Place): boolean {
  if (!PRUNE_THIN_ON) return true;
  if (p.source !== "dfp" && p.source !== "google") return true;
  // Any real signal keeps it: a Google rating, a photo of ANY kind
  // (Google enrichment, seed hero, or a Wikimedia landmark match), or
  // a real editorial summary. Hidden only when it has NONE of these —
  // a name + category + point and nothing else.
  if (p.hero_image || getLandmarkPhoto(p.slug)) return true;
  const e = ENRICHMENT[p.slug];
  if (!e) return false;
  return Boolean(
    e.rating ||
      (e.photo_names && e.photo_names.length > 0) ||
      (e.editorial_summary && e.editorial_summary.trim().length > 0),
  );
}

/**
 * P0-1: the ONE canonical public place set. Every non-admin surface
 * (Radius/home, Map, Search, Municipality, Saved, Sitemap, Plan) must
 * start here so users see the same reality on every route: deduplicated
 * (gated by RADIUS_DEDUPE), closed businesses removed, the non-
 * discoverable B2B long tail quieted (gated by RADIUS_RELEVANCE), AND
 * coordinates validated against the county bbox so a mispositioned
 * marker can never reach a user. Off-bbox rows surface on
 * /admin/data-health via getNeedsReviewPlaces() so they are visible
 * to an editor before they are invisible to the world.
 */
export function publicPlaces(): Place[] {
  return BASE_PLACES
    .filter(isOperational)
    .filter(isDiscoverable)
    .filter(isSubstantive)
    .filter((p) => isValidCoord(p.geom));
}

/**
 * Places whose coordinate is missing or outside the Frederick County
 * bbox. These are dropped from every public surface and listed in
 * /admin/data-health so an editor can fix them.
 */
export function getNeedsReviewPlaces(): Place[] {
  return BASE_PLACES.filter((p) => !isValidCoord(p.geom));
}

/** Public places in one municipality (canonical set, not raw). */
export function publicPlacesByMunicipality(slug: string): Place[] {
  return publicPlaces().filter((p) => p.municipality === slug);
}

/**
 * Resolve a slug to its canonical public place. Folded-duplicate and
 * old slugs resolve to the canonical record (BASE_BY_SLUG already does
 * this); closed or unknown slugs return undefined so saved/linked
 * closed records do not render.
 */
export function publicPlaceBySlug(slug: string): Place | undefined {
  const p = BASE_BY_SLUG[slug];
  return p && isOperational(p) ? p : undefined;
}

/** Back-compat alias. Prefer publicPlaces() in new code. */
export function radiusPlaces(): Place[] {
  return publicPlaces();
}

/**
 * Marquee places whose curated reliable window says they are open now,
 * tagged "likely". Used as the home "Open now" fallback when Google has
 * not verified anything, so the panel never shows a defeating empty
 * state. Closed places are still excluded.
 */
export function likelyOpenPlaces(origin?: LngLat, now: Date = new Date()): PlaceCardData[] {
  return BASE_PLACES
    .filter(isOperational)
    .filter(isDiscoverable)
    .filter(isSubstantive)
    .filter((p) => p.slug in RELIABLE_OPEN_WINDOWS && isLikelyOpenNow(p.slug, now))
    .map((p) => ({ ...decoratePlace(p, origin, now), open_confidence: "likely" as const }))
    .sort((a, b) => (a.distance_m ?? Infinity) - (b.distance_m ?? Infinity));
}

export function rankPlaces(ctx: RankingContext = {}): PlaceCardData[] {
  const now = ctx.now ?? new Date();
  let results = BASE_PLACES
    .filter(isOperational)
    .filter(isDiscoverable)
    .filter(isSubstantive)
    .map((p) => decoratePlace(p, ctx.origin, now));

  if (ctx.category) {
    results = results.filter(
      (p) => p.category === ctx.category || (p.subcategories ?? []).includes(ctx.category!)
    );
  }
  if (ctx.municipality) {
    results = results.filter((p) => p.municipality === ctx.municipality);
  }
  if (ctx.tags?.length) {
    results = results.filter((p) => ctx.tags!.every((t) => (p.tags ?? []).includes(t)));
  }
  if (ctx.preferOpen) {
    results = results.filter((p) => p.open_status.state !== "closed");
  }

  results.sort((a, b) => {
    const sa = a.feature_score * 0.4 + proximityScore(a.distance_m) * 0.3 + openScore(a.open_status) * 0.3;
    const sb = b.feature_score * 0.4 + proximityScore(b.distance_m) * 0.3 + openScore(b.open_status) * 0.3;
    return sb - sa;
  });

  return ctx.limit ? results.slice(0, ctx.limit) : results;
}

export function placesWithinRadius(origin: LngLat, meters: number, now: Date = new Date()): PlaceCardData[] {
  return BASE_PLACES
    .filter(isOperational)
    .filter(isDiscoverable)
    .filter(isSubstantive)
    .map((p) => decoratePlace(p, origin, now))
    .filter((p) => (p.distance_m ?? Infinity) <= meters)
    .sort((a, b) => (a.distance_m ?? Infinity) - (b.distance_m ?? Infinity));
}
