/* This file is generated by scripts/build-fair-pack.ts. Do not edit. */
import releaseJson from "../../../public/fair/2026/releases/cd119be7f282d497d948f68ddccc1c7152e5cc178cc5557ac23eb83f3dde5bc9.json";
import pointerJson from "../../../public/fair/2026/current.json";

import { parseFairPack, parseFairPackPointer } from "@/lib/fair/pack";

export const greatFrederickFair2026Pack = parseFairPack(releaseJson);
export const greatFrederickFair2026PackPointer = parseFairPackPointer(pointerJson);
