/* This file is generated by scripts/build-fair-pack.ts. Do not edit. */
import releaseJson from "../../../public/fair/2026/releases/3076104cfce3b3cd30e4a5501fdc64a735755390f69d3d2d99e905208b105e6d.json";
import pointerJson from "../../../public/fair/2026/current.json";

import { parseFairPack, parseFairPackPointer } from "@/lib/fair/pack";

export const greatFrederickFair2026Pack = parseFairPack(releaseJson);
export const greatFrederickFair2026PackPointer = parseFairPackPointer(pointerJson);
