/* This file is generated by scripts/build-fair-pack.ts. Do not edit. */
import releaseJson from "../../../public/fair/2026/releases/f2f1b4009bef6db75c7629380ff66592541cfb0fc30e430c9986b2e85f6f742e.json";
import pointerJson from "../../../public/fair/2026/current.json";

import { parseFairPack, parseFairPackPointer } from "@/lib/fair/pack";

export const greatFrederickFair2026Pack = parseFairPack(releaseJson);
export const greatFrederickFair2026PackPointer = parseFairPackPointer(pointerJson);
