/**
 * Generate src/data/photo-suppress.json — the deterministic shared-photo
 * suppression list.
 *
 * THE PROBLEM: ~74 Google "photo clusters" exist where multiple public
 * records share the SAME Google photo (`photo_names[0]` resolves to one
 * ChIJ place id) — multi-tenant buildings, wrong-photo bad matches, and
 * mis-geocoded dupes. The visible result: two adjacent cards with the same
 * photo, or a wrong photo on a place. That makes good data look scraped.
 *
 * THE RULE (no photo > wrong photo): for each ChIJ cluster with >1 public
 * record, keep the photo on ONE canonical record and suppress it on the
 * rest (they fall back to the existing category placeholder in the card).
 * Canonical = feature_score desc, then source rank (curated seed/manual >
 * dfp/google), then rating count, then slug — the best record wins.
 *
 * Deterministic + reviewable: the output JSON is committed and read by the
 * loader. Regenerate after a photo re-enrichment: `npm run build:photo-suppress`.
 */
import { writeFileSync } from "node:fs";
import ENRICHMENT_RAW from "../src/data/places-enrichment.json" with { type: "json" };
import { publicPlaces } from "../src/lib/loaders/places";

const ENR = ENRICHMENT_RAW as Record<string, { photo_names?: string[]; user_rating_count?: number }>;
// Lower rank = more trusted, used only as a tiebreak after feature_score.
const SRC_RANK: Record<string, number> = { seed: 0, manual: 1, arcgis: 2, yelp: 3, google: 4, dfp: 5 };

type Rec = { slug: string; fs: number; src: string; rc: number };
const clusters = new Map<string, Rec[]>();
for (const p of publicPlaces()) {
  const pn = ENR[p.slug]?.photo_names?.[0];
  const m = pn && /(ChIJ[A-Za-z0-9_-]+)/.exec(pn);
  if (!m) continue;
  const rec: Rec = { slug: p.slug, fs: p.feature_score, src: p.source, rc: ENR[p.slug]?.user_rating_count ?? 0 };
  const arr = clusters.get(m[1]) ?? [];
  arr.push(rec);
  clusters.set(m[1], arr);
}

const suppressed: string[] = [];
let clustersFixed = 0;
for (const recs of clusters.values()) {
  if (recs.length < 2) continue;
  clustersFixed++;
  const canonical = [...recs].sort(
    (a, b) =>
      b.fs - a.fs ||
      (SRC_RANK[a.src] ?? 9) - (SRC_RANK[b.src] ?? 9) ||
      b.rc - a.rc ||
      a.slug.localeCompare(b.slug),
  )[0];
  for (const r of recs) if (r.slug !== canonical.slug) suppressed.push(r.slug);
}
suppressed.sort();

writeFileSync(
  "src/data/photo-suppress.json",
  JSON.stringify(
    {
      _doc:
        "Slugs whose hero photo is suppressed (shared-photo de-twin). Generated by scripts/build-photo-suppress.ts; do not hand-edit. Canonical per ChIJ photo cluster keeps the photo; the rest fall back to the category placeholder.",
      clusters_fixed: clustersFixed,
      count: suppressed.length,
      slugs: suppressed,
    },
    null,
    0,
  ) + "\n",
);
console.log(`photo-suppress: ${clustersFixed} clusters, ${suppressed.length} slugs suppressed → src/data/photo-suppress.json`);
