/**
 * Build the provider-identity snapshot used by paid hours/status refreshes and
 * by the read-only hours materialization.
 *
 * Public visibility is intentionally not part of this artifact. Closed and
 * off-season places remain present so a provider can later report that they
 * reopened, while the canonical loader still enforces dedupe, placement,
 * relevance, substance, quarantine, and accepted Google identity.
 */
import { writeFileSync } from "node:fs";
import {
  canonicalPlaceRefreshIdentities,
  type PlaceRefreshIdentity,
} from "@/lib/loaders/places";
import { findGooglePlaceIdCollisions } from "@/lib/quality/enrichmentBinding";

const OUT = new URL(
  "../src/data/place-refresh-identities.json",
  import.meta.url,
).pathname;

const identities: PlaceRefreshIdentity[] =
  canonicalPlaceRefreshIdentities();
const collisions = findGooglePlaceIdCollisions(identities);
if (collisions.length > 0) {
  const detail = collisions
    .map(
      ({ googlePlaceId, slugs }) =>
        `${googlePlaceId}: ${slugs.join(", ")}`,
    )
    .join("\n");
  throw new Error(
    `Refusing to publish canonical refresh identities with duplicate Google Place IDs:\n${detail}`,
  );
}

const artifact = {
  _doc:
    "Canonical accepted Google identities and Radius categories before live business-status and seasonal visibility gates. Closed and off-season places remain here so status refreshes can discover a reopening, while paid hours refreshes can select only time-sensitive food and drink categories. Generated by npm run build:place-refresh-identities; do not edit by hand.",
  _meta: {
    schema_version: 2,
    count: identities.length,
  },
  identities,
};

writeFileSync(OUT, `${JSON.stringify(artifact, null, 2)}\n`);
console.log(`wrote ${OUT} — ${identities.length} canonical Google identities`);
