/**
 * fetch-town-photo-candidates.ts — assemble a license-cleared candidate sheet
 * of Wikimedia Commons HERO photos for each municipality, for by-eye approval.
 *
 * The /m town page falls back to generic seasonal county photography because no
 * town has its own hero (TOWN_PHOTOS in wikimedia.ts is empty). This queries the
 * keyless Commons API for each town's category and writes a review sheet with
 * thumbnails + license + author so the owner can pick the right shot — then the
 * approved File: names get added to TOWN_PHOTOS (verified:true).
 *
 * It does NOT ship any image: choosing a photo that actually depicts the town
 * well is a by-eye call (the same discipline that caught the bad place heroes).
 *
 *   npx tsx scripts/fetch-town-photo-candidates.ts   → docs/town-photo-candidates.md
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { MUNICIPALITIES } from "../src/data/municipalities";

const API = "https://commons.wikimedia.org/w/api.php";
const OUT = resolve(process.cwd(), "docs/town-photo-candidates.md");

// Disambiguation-prone names get explicit Commons categories (several US towns
// share these names). Tried in order until one returns files.
const OVERRIDE: Record<string, string[]> = {
  frederick: ["Frederick, Maryland"],
  middletown: ["Middletown, Frederick County, Maryland", "Middletown, Maryland"],
  "new-market": ["New Market, Frederick County, Maryland", "New Market, Maryland"],
  "mount-airy": ["Mount Airy, Maryland"],
  rosemont: ["Rosemont, Frederick County, Maryland"],
  urbana: ["Urbana, Frederick County, Maryland", "Urbana, Maryland"],
};
const categoriesFor = (m: { slug: string; name: string }): string[] =>
  OVERRIDE[m.slug] ?? [`${m.name.replace(/^Downtown /, "")}, Maryland`];

const strip = (h?: string) => (h ?? "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
// Drop non-photo / non-town files.
const BAD = /seal|logo|flag|coat of arms|\.svg|\.pdf|\.ogg|map of|locator|wikivoyage|banner|panoramio.*sign/i;

type Cand = { file: string; thumb: string; url: string; license: string; author: string; desc: string };

async function fetchCategory(cat: string): Promise<Cand[]> {
  const u = new URL(API);
  u.search = new URLSearchParams({
    action: "query", format: "json", generator: "categorymembers",
    gcmtitle: `Category:${cat}`, gcmtype: "file", gcmlimit: "60",
    prop: "imageinfo", iiprop: "url|extmetadata", iiurlwidth: "320",
  }).toString();
  const r = await fetch(u, { headers: { "User-Agent": "FrederickRadius/1.0 (town-photo-audit)" } });
  if (!r.ok) return [];
  const j = (await r.json()) as { query?: { pages?: Record<string, {
    title: string;
    imageinfo?: Array<{ url: string; thumburl?: string; extmetadata?: Record<string, { value?: string }> }>;
  }> } };
  const pages = j.query?.pages ? Object.values(j.query.pages) : [];
  return pages
    .map((p): Cand | null => {
      const ii = p.imageinfo?.[0];
      if (!ii) return null;
      const em = ii.extmetadata ?? {};
      const file = p.title.replace(/^File:/, "");
      return {
        file,
        thumb: ii.thumburl ?? "",
        url: ii.url,
        license: strip(em.LicenseShortName?.value) || "?",
        author: strip(em.Artist?.value) || "?",
        desc: strip(em.ImageDescription?.value).slice(0, 90),
      };
    })
    .filter((c): c is Cand => c !== null && !BAD.test(c.file));
}

async function main() {
  const lines: string[] = [
    "# Town hero photo candidates (Wikimedia Commons)",
    "",
    "Generated by `npm run fetch:town-photos`. Each town shows up to 6 license-cleared",
    "Commons candidates. **Pick the one that best depicts the town** (Main Street, downtown,",
    "the signature landmark/station) and add it to `TOWN_PHOTOS` in",
    "`src/lib/integrations/wikimedia.ts` with `verified: true`. Nothing ships until you do.",
    "",
  ];

  for (const m of MUNICIPALITIES) {
    let cands: Cand[] = [];
    let usedCat = "";
    for (const cat of categoriesFor(m)) {
      cands = await fetchCategory(cat);
      usedCat = cat;
      if (cands.length) break;
      await new Promise((r) => setTimeout(r, 150));
    }
    lines.push(`## ${m.name} \`${m.slug}\` — Category: ${usedCat} (${cands.length} candidate${cands.length === 1 ? "" : "s"})`, "");
    if (!cands.length) {
      lines.push("_No Commons category photos found — try Library of Congress (loc.gov, public domain) or shoot it yourself._", "");
      continue;
    }
    for (const c of cands.slice(0, 6)) {
      lines.push(
        `- ![thumb](${c.thumb})  `,
        `  **File:** \`${c.file}\` — ${c.license} — ${c.author}`,
        c.desc ? `  _${c.desc}_` : "",
        `  FilePath: https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(c.file)}?width=1200`,
        "",
      );
    }
    await new Promise((r) => setTimeout(r, 150));
  }

  writeFileSync(OUT, lines.filter((l) => l !== undefined).join("\n"));
  console.log(`wrote ${OUT} — ${MUNICIPALITIES.length} towns`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
