/**
 * Generated by `npm run blob:static-assets`.
 *
 * Maps committed public asset paths to their Vercel Blob URLs. It starts empty
 * so the app keeps serving local assets until the upload script is run and the
 * generated diff is reviewed.
 */
export const BLOB_STATIC_ASSETS: Record<string, string> = {};
